# Generated by Django 3.2.6 on 2021-11-01 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Edición'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Edición'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Edición'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='seccion',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
