# Generated by Django 3.2.6 on 2021-11-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_auto_20211101_0208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['created'], 'verbose_name': 'articulo'},
        ),
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['created'], 'verbose_name': 'cliente'},
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'ordering': ['created'], 'verbose_name': 'pedido'},
        ),
        migrations.AlterModelTable(
            name='articulo',
            table='articulos',
        ),
        migrations.AlterModelTable(
            name='clientes',
            table='clientes',
        ),
        migrations.AlterModelTable(
            name='pedidos',
            table='pedidos',
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Edición')),
                ('detalleArticulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detalleArticulo', to='tiendaApp.articulo')),
                ('detallePedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='detallePedido', to='tiendaApp.pedidos')),
            ],
            options={
                'verbose_name': 'detalle',
                'db_table': 'detalles',
                'ordering': ['created'],
            },
        ),
    ]
