# Generated by Django 3.2.6 on 2021-11-01 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_auto_20211101_0314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetallePedido',
            new_name='DetallePedidos',
        ),
    ]
