# Generated by Django 3.2.6 on 2021-11-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0004_rename_detallepedido_detallepedidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='nro_pedidos',
            new_name='nro_pedido',
        ),
    ]
